image: debian/buster
environment:
  APP: bpf-demo
  REPO: docker.io/alexeldeib
packages:
- curl
- gpg
- apt-transport-https
- fio
repositories: null
secrets:
- 7bb48981-fc03-4344-bae3-736c99f94f49
- 21bdadaa-095c-4968-9a6e-ce9b795042b4
shell: null
sources:
- https://github.com/alexeldeib/bpf-demo
tasks:
- install: |
    bash ~/bpf-demo/build/setup_docker.sh
- build: |
    bash ~/bpf-demo/build/build.sh
